//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inscripcionesbol.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDocente
    {
        public TDocente()
        {
            this.TCurso = new HashSet<TCurso>();
        }
    
        public int Id_Docente { get; set; }
        public string Nombre_Doc { get; set; }
        public string Apellido_Doc { get; set; }
    
        public virtual ICollection<TCurso> TCurso { get; set; }
    }
}
