//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inscripcionesbol.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEstudiante
    {
        public TEstudiante()
        {
            this.TInscripciones = new HashSet<TInscripciones>();
        }
    
        public int Id_Estudiante { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Edad { get; set; }
        public string Genero { get; set; }
        public string Celular { get; set; }
        public string Tipo { get; set; }
        public string Ci_Estudiante { get; set; }
        public string Monto { get; set; }
    
        public virtual ICollection<TInscripciones> TInscripciones { get; set; }
    }
}
