//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inscripcionesbol.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TInscripciones
    {
        public int Id_Inscripciones { get; set; }
        public string Monto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Id_Estudiante { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<int> Id_Curso { get; set; }
    
        public virtual TCurso TCurso { get; set; }
        public virtual TEstudiante TEstudiante { get; set; }
        public virtual TUsuario TUsuario { get; set; }
    }
}
