//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inscripcionesbol.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUsuario
    {
        public TUsuario()
        {
            this.TInscripciones = new HashSet<TInscripciones>();
        }
    
        public int Id_Usuario { get; set; }
        public string Cuenta { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Rol { get; set; }
        public string Genero { get; set; }
    
        public virtual ICollection<TInscripciones> TInscripciones { get; set; }
    }
}
